massive revamp

diff --git a/install/tests/Makefile b/install/tests/Makefile
--- a/install/tests/Makefile
+++ b/install/tests/Makefile
@@ -5,7 +5,13 @@ PROJECTNAME := "installer-nightly-tests"
 
 TOPDIR=$(shell pwd)
 
-KUBECONFIG := "$(TOPDIR)/kubeconfig"
+KUBECONFIG := "/workspace/conf"
+
+cloud_k3s := "gcp"
+cloud_gke := "gcp"
+cloud_aks := "azure"
+cloud_eks := "aws"
+
 
 check-env-sub-domain:
 ifndef TF_VAR_TEST_ID
@@ -21,47 +27,44 @@ help: Makefile
 	@sed -n 's/^##//p' $< | column -t -s ':' |  sed -e 's/^/ /'
 	@echo
 
+cluster ?= gke
 .PHONY:
-## gke-standard-cluster: Creates a zonal GKE cluster
-gke-standard-cluster:
+## create-cluster: Creates a cluster
+create-cluster:
 	terraform init --upgrade && \
 	terraform workspace new $(TF_VAR_TEST_ID) || terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.gke -var kubeconfig=${KUBECONFIG} --auto-approve
+	terraform apply -target=module.$(cluster) -var kubeconfig=${KUBECONFIG} --auto-approve
 
+cluster ?= gke
 .PHONY:
-## eks-standard-cluster: Creates an EKS cluster
-eks-standard-cluster:
-	terraform init --upgrade && \
-	terraform workspace new $(TF_VAR_TEST_ID) || terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.eks -var kubeconfig=${KUBECONFIG} --auto-approve
+## cleanup-cluster: Creates a cluster
+cleanup-cluster: select-workspace
+	terraform destroy -target=module.$(cluster) -var kubeconfig=${KUBECONFIG} --auto-approve
 
-.PHONY:
-## aks-standard-cluster: Creates an AKS cluster
-aks-standard-cluster:
-	terraform init --upgrade && \
-	terraform workspace new $(TF_VAR_TEST_ID) || terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.aks -var k8s_flavor="aks" -var kubeconfig=${KUBECONFIG} --auto-approve
-
+cluster ?= gke
 .PHONY:
 ## add-ns-record: Adds NS record for subdomain under gitpod-selfhosted.com
+add-ns-record: cloud = $(cloud_$(cluster))
 add-ns-record:
 	terraform init --upgrade && \
 	terraform workspace new $(TF_VAR_TEST_ID) || terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.add_gcp_nameservers  -var kubeconfig=${KUBECONFIG} --auto-approve
+	terraform apply -target=module.$(cloud)-add-ns-record  -var kubeconfig=${KUBECONFIG} --auto-approve
 
+cluster ?= gke
 .PHONY:
-## azure-issuer: Creates a cluster issuer with AD access
-azure-issuer:
+## cleanup-ns-record: Deletes NS record for subdomain under gitpod-selfhosted.com
+cleanup-ns-record: cloud = $(cloud_$(cluster))
+cleanup-ns-record: select-workspace
+	terraform destroy -target=module.$(cloud)-add-ns-record  -var kubeconfig=${KUBECONFIG} --auto-approve
+
+cluster ?= gke
+.PHONY:
+## cluster-issuer: Creates a cluster issuer
+cluster-issuer: cloud = $(cloud_$(cluster))
+cluster-issuer:
 	terraform init --upgrade && \
 	terraform workspace new $(TF_VAR_TEST_ID) || terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.azure-issuer  -var kubeconfig=${KUBECONFIG} --auto-approve
-
-.PHONY:
-## k3s-standard-cluster: Creates a K3S cluster on GCP with one master and 1 worker node
-k3s-standard-cluster:
-	terraform init --upgrade && \
-	terraform workspace new $(TF_VAR_TEST_ID) || terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.k3s -var kubeconfig=${KUBECONFIG} --auto-approve
+	terraform apply -target=module.$(cloud)-issuer  -var kubeconfig=${KUBECONFIG} --auto-approve
 
 CLUSTER_ISSUER_CLOUD_DNS := "./manifests/gcp-issuer.yaml"
 
@@ -71,19 +74,15 @@ cert-manager:
 	terraform workspace select $(TF_VAR_TEST_ID) && \
 	terraform apply -target=module.certmanager -var kubeconfig=${KUBECONFIG} --auto-approve
 
-.PHONY:
-## managed-dns: Installs external-dns, and setup up CloudDNS access
-managed-dns: check-env-sub-domain
-	terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.clouddns-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve && \
-    kubectl --kubeconfig=${KUBECONFIG} apply -f ${CLUSTER_ISSUER_CLOUD_DNS}
-
-provider ?= "azure"
+cluster ?= gke
 .PHONY:
 ## external-dns: Installs external-dns
+external-dns: cloud = $(cloud_$(cluster))
 external-dns: check-env-sub-domain
 	terraform workspace select $(TF_VAR_TEST_ID) && \
-	terraform apply -target=module.externaldns -var provider=${provider} -var kubeconfig=${KUBECONFIG} --auto-approve
+	terraform apply -target=module.$(cloud)-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve
+
+    # kubectl --kubeconfig=${KUBECONFIG} apply -f ${CLUSTER_ISSUER_CLOUD_DNS}
 
 .PHONY:
 ## get-kubeconfig: Returns KUBECONFIG of a just created cluster
@@ -95,62 +94,57 @@ KOTS_KONFIG := "./manifests/kots-config.yaml"
 get-base-config:
 	envsubst < ${KOTS_KONFIG} > tmp_config.yml
 
-get-config-incluster:
+storage-config-aws:
 	@echo "Nothing to do"
 
-get-config-gcp-storage: config-file = "./manifests/kots-config-gcp-storage.yaml"
-get-config-gcp-storage:
+db-config-aws:
+	@echo "Nothing to do"
+
+registry-config-aws:
+	@echo "Nothing to do"
+
+storage-config-incluster:
+	@echo "Nothing to do"
+
+db-config-incluster:
+	@echo "Nothing to do"
+
+registry-config-incluster:
+	@echo "Nothing to do"
+
+storage-config-gcp: config-file = "./manifests/kots-config-gcp-storage.yaml"
+storage-config-gcp:
 	export BASE64_GCP_KEY=$$(cat $$TF_VAR_sa_creds | tr -d '\n' | base64 -w 0) && \
 	envsubst '$${BASE64_GCP_KEY}' < ${config-file} > tmp_2_config.yml
 	yq m -i tmp_config.yml tmp_2_config.yml
 
-get-config-gcp-registry: config-file = "./manifests/kots-config-gcp-registry.yaml"
-get-config-gcp-registry:
+registry-config-gcp: config-file = "./manifests/kots-config-gcp-registry.yaml"
+registry-config-gcp:
 	export GCP_KEY=$$(cat $$TF_VAR_sa_creds | tr -d '\n' | base64 -w 0) && \
 	envsubst '$${GCP_KEY}' < ${config-file} > tmp_4_config.yml
 	yq m -i tmp_config.yml tmp_4_config.yml
 
-get-config-gcp-db: config-file = "./manifests/kots-config-gcp-db.yaml"
-get-config-gcp-db:
+db-config-gcp: config-file = "./manifests/kots-config-gcp-db.yaml"
+db-config-gcp:
 	export BASE64_GCP_KEY=$$(cat $$TF_VAR_sa_creds | tr -d '\n' | base64 -w 0) && \
 	envsubst '$${BASE64_GCP_KEY}' < ${config-file} > tmp_4_config.yml
 	envsubst '$${TF_VAR_TEST_ID}' < tmp_4_config.yml > tmp_5_config.yml
 	yq m -i tmp_config.yml tmp_5_config.yml
 
-get-config-azure-storage:
+storage-config-azure:
 	export PASSWORD=$$(terraform output -json storage | yq r - 'password') && \
 	export USERNAME=$$(terraform output -json storage | yq r - 'username') && \
 	envsubst < ./manifests/kots-config-azure-storage.yaml > tmp_2_config.yml
 	yq m -i tmp_config.yml tmp_2_config.yml
 
-get-config-azure-db:
+db-config-azure:
 	export DBHOST=$$(terraform output -json database | yq r - 'host') && \
 	export DBPASS=$$(terraform output -json database | yq r - 'password') && \
 	export DBUSER=$$(terraform output -json database | yq r - 'username') && \
 	envsubst < ./manifests/kots-config-azure-db.yaml > tmp_2_config.yml
 	yq m -i tmp_config.yml tmp_2_config.yml
 
-get-config-azure-registry:
-	export SERVER=$$(terraform output -json registry | yq r - 'server') && \
-	export PASSWORD=$$(terraform output -json registry | yq r - 'password') && \
-	export USERNAME=$$(terraform output -json registry | yq r - 'username') && \
-	envsubst < ./manifests/kots-config-azure-registry.yaml > tmp_2_config.yml
-	yq m -i tmp_config.yml tmp_2_config.yml
-
-get-config-azure-storage:
-	export PASSWORD=$$(terraform output -json storage | yq r - 'password') && \
-	export USERNAME=$$(terraform output -json storage | yq r - 'username') && \
-	envsubst < ./manifests/kots-config-azure-storage.yaml > tmp_2_config.yml
-	yq m -i tmp_config.yml tmp_2_config.yml
-
-get-config-azure-db:
-	export DBHOST=$$(terraform output -json database | yq r - 'host') && \
-	export DBPASS=$$(terraform output -json database | yq r - 'password') && \
-	export DBUSER=$$(terraform output -json database | yq r - 'username') && \
-	envsubst < ./manifests/kots-config-azure-db.yaml > tmp_2_config.yml
-	yq m -i tmp_config.yml tmp_2_config.yml
-
-get-config-azure-registry:
+registry-config-azure:
 	export SERVER=$$(terraform output -json registry | yq r - 'server') && \
 	export PASSWORD=$$(terraform output -json registry | yq r - 'password') && \
 	export USERNAME=$$(terraform output -json registry | yq r - 'username') && \
@@ -161,8 +155,11 @@ storage ?= incluster
 registry ?= incluster
 db ?= incluster
 .PHONY:
+generate-kots-config: storage = $(if $(storage:incluster=),$(cloud_$(storage)),$(storage))
+generate-kots-config: registry = $(if $(registry:incluster=),$(cloud_$(registry)),$(registry))
+generate-kots-config: registry = $(if $(registry:db=),$(cloud_$(db)),$(db))
 ## generate-kots-config: Generate the kots config based on test config
-generate-kots-config: get-base-config get-config-${storage} get-config-${registry} get-config-${db}
+generate-kots-config: get-base-config storage-config-${storage} registry-config-${registry} db-config-${db}
 
 license_community_beta := "../licenses/Community (Beta).yaml"
 license_community_stable := "../licenses/Community.yaml"
@@ -203,37 +200,23 @@ kots-uprgade:
 	@echo "Upgrade gitpod KOTS app to latest"
 	kubectl kots upstream upgrade --kubeconfig=${KUBECONFIG} gitpod -n gitpod --deploy
 
-cleanup: destroy-gcp-externaldns destroy-gcpns destroy-aks-edns destroy-aks-issuer destroy-certmanager destroy-clusters
-
 select-workspace:
 	terraform workspace select $(TF_VAR_TEST_ID)
 
-destroy-gcp-externaldns: select-workspace
-	ls ${KUBECONFIG} && terraform destroy -target=module.clouddns-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-
-destroy-certmanager: select-workspace
+cluster ?= gke
+## cleanup: Clean up the created infrastructure
+cleanup: cloud = $(cloud_$(cluster))
+cleanup: select-workspace
+	terraform destroy -target=module.$(cloud)-add-ns-record -var kubeconfig=${KUBECONFIG} --auto-approve
 	ls ${KUBECONFIG} && terraform destroy -target=module.certmanager -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-
-destroy-gcpns: select-workspace
-	terraform destroy -target=module.add_gcp_nameservers -var kubeconfig=${KUBECONFIG} --auto-approve
-
-destroy-edns: select-workspace
-	ls ${KUBECONFIG} && terraform destroy -target=module.externaldns -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-
-destroy-aks-issuer: select-workspace
-	ls ${KUBECONFIG} && terraform destroy -target=module.azure-issuer -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
-
-destroy-clusters: select-workspace
-	terraform destroy -target=module.gke -var kubeconfig=${KUBECONFIG} --auto-approve
-	terraform destroy -target=module.eks -var kubeconfig=${KUBECONFIG} --auto-approve
-	terraform destroy -target=module.k3s -var kubeconfig=${KUBECONFIG} --auto-approve
-	[ -z "$$ARM_SUBSCRIPTION_ID" ] || terraform destroy -target=module.aks -var kubeconfig=${KUBECONFIG} --auto-approve
+	ls ${KUBECONFIG} && terraform destroy -target=module.$(cloud)-externaldns -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
+	ls ${KUBECONFIG} && terraform destroy -target=module.$(cloud)-issuer -var kubeconfig=${KUBECONFIG} --auto-approve || echo "No kubeconfig file"
+	terraform destroy -target=module.$(cluster) -var kubeconfig=${KUBECONFIG} --auto-approve
 
 get-results:
 	@echo "If you have gotten this far, it means your setup succeeded"
 	@echo "The IP address of you setup is "$(TF_VAR_TEST_ID).gitpod-self-hosted.com""
 	@echo "Following is the KUBECONFIG you can use to connect to the cluster:"
-	@cat tmp_config.yml
 	@cat ${KUBECONFIG}
 
 list-state:
