fix

diff --git a/.werft/ide-integration-tests-startup-vscode.yaml b/.werft/ide-integration-tests-startup-vscode.yaml
--- a/.werft/ide-integration-tests-startup-vscode.yaml
+++ b/.werft/ide-integration-tests-startup-vscode.yaml
@@ -25,6 +25,21 @@ pod:
         secretKeyRef:
           name: github-roboquat-automatic-changelog
           key: token
+    - name: USERNAME
+      valueFrom:
+        secretKeyRef:
+          name: integration-test-user
+          key: username
+    - name: USER_TOKEN
+      valueFrom:
+        secretKeyRef:
+          name: integration-test-user
+          key: token
+    - name: SLACK_NOTIFICATION_PATH
+      valueFrom:
+        secretKeyRef:
+          name: slack-webhook-urls
+          key: ide_jobs
     volumeMounts:
     - name: gcp-sa
       mountPath: /mnt/secrets/gcp-sa
@@ -38,17 +53,63 @@ pod:
     - |
       set -euo pipefail
 
+      sudo chown -R gitpod:gitpod /workspace
+
+      # Fix weird repeat running behavior
+      LAST_COMMIT_MSG=$(git log --pretty=format:"%s" -1)
+      if [[ $LAST_COMMIT_MSG =~ "integration test" ]]; then exit 0; fi
+
       BRANCH="inte-test/"$(date +%Y%m%d%H%M%S)
+
+      export WERFT_CREDENTIAL_HELPER=/workspace/dev/preview/werft-credential-helper.sh
+
+      FAILURE_COUNT=0
+      RUN_COUNT=0
+      declare -A FAILURE_TESTS
 
       function cleanup ()
       {
-        git push origin :$BRANCH
+        werft log phase "slack notification" "slack notification"
+        context_name="{{ .Name }}"
+        context_repo="{{ .Repository.Repo }}"
+        werftJobUrl="https://werft.gitpod-dev.com/job/${context_name}"
+
+        if [ "${RUN_COUNT}" -eq "0" ]; then
+          title=":x: *IDE integration test fail*"
+          title=$title"\n_Repo:_ ${context_repo}\n_Build:_ ${context_name}"
+
+          errs="Failed at preparing the preview environment"
+          BODY="{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${title}\"},\"accessory\":{\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"text\":\":werft: Go to Werft\",\"emoji\":true},\"value\":\"click_me_123\",\"url\":\"${werftJobUrl}\",\"action_id\":\"button-action\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"\`\`\`\\n${errs}\\n\`\`\`\"}}]}"
+        elif [ "${FAILURE_COUNT}" -ne "0" ]; then
+          title=":x: *IDE integration test fail*"
+          title=$title"\n_Repo:_ ${context_repo}\n_Build:_ ${context_name}"
+
+          errs=""
+          for TEST_NAME in ${!FAILURE_TESTS[*]}; do
+            title=$title"\n_Tests_: ${TEST_NAME}"
+            errs+="${FAILURE_TESTS["${TEST_NAME}"]}"
+          done
+          errs=$(echo "${errs}" | head)
+          BODY="{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${title}\"},\"accessory\":{\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"text\":\":werft: Go to Werft\",\"emoji\":true},\"value\":\"click_me_123\",\"url\":\"${werftJobUrl}\",\"action_id\":\"button-action\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"\`\`\`\\n${errs}\\n\`\`\`\"}}]}"
+        else
+          title=":white_check_mark: *IDE integration test pass*"
+
+          title=$title"\n_Repo:_ ${context_repo}\n_Build:_ ${context_name}"
+          BODY="{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${title}\"},\"accessory\":{\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"text\":\":werft: Go to Werft\",\"emoji\":true},\"value\":\"click_me_123\",\"url\":\"${werftJobUrl}\",\"action_id\":\"button-action\"}}]}"
+        fi
+
+        curl -X POST \
+          -H 'Content-type: application/json' \
+          -d "${BODY}" \
+          "https://hooks.slack.com/${SLACK_NOTIFICATION_PATH}"
+        werft log result "slack notification" "${PIPESTATUS[0]}"
+
+        werft log phase "clean up" "clean up"
+        git push origin :"${BRANCH}" | werft log slice "clean up"
+        werft log slice "clean up" --done
       }
 
-      source ./dev/preview/util/preview-name-from-branch.sh
-
       echo "preparing config." | werft log slice prepare
-      sudo chown -R gitpod:gitpod /workspace
       gcloud auth activate-service-account --key-file /mnt/secrets/gcp-sa/service-account.json
       export GOOGLE_APPLICATION_CREDENTIALS="/home/gitpod/.config/gcloud/legacy_credentials/cd-gitpod-deployer@gitpod-core-dev.iam.gserviceaccount.com/adc.json"
 
@@ -57,7 +118,6 @@ pod:
       git remote set-url origin https://oauth2:$ROBOQUAT_TOKEN@github.com/gitpod-io/gitpod.git
 
       echo "copied config..." | werft log slice prepare
-      go install github.com/csweichel/oci-tool@latest 2>&1 | werft log slice prepare
       werft log slice prepare --done
 
       werft log phase "build preview environment" "build preview environment"
@@ -66,13 +126,15 @@ pod:
       git add README.md
       git commit -m "integration test"
       git push --set-upstream origin $BRANCH
+      werft run github -a with-preview=true
+
       trap cleanup SIGINT SIGTERM EXIT
 
-      BUILD_ID=$(werft job list repo.ref==refs/heads/${BRANCH} -o yaml | yq r - "result[0].name")
+      BUILD_ID=$(werft job list repo.ref==refs/heads/${BRANCH} -o yaml | yq4 '.result[] | select(.metadata.annotations[].key == "with-preview") | .name' | head -1)
       until [ "$BUILD_ID" != "" ]
       do
           sleep 1
-          BUILD_ID=$(werft job list repo.ref==refs/heads/${BRANCH} -o yaml | yq r - "result[0].name")
+          BUILD_ID=$(werft job list repo.ref==refs/heads/${BRANCH} -o yaml | yq4 '.result[] | select(.metadata.annotations[].key == "with-preview") | .name' | head -1)
       done
       echo "start build preview environment, job name: ${BUILD_ID}, this will take long time" | werft log slice "build test environment"
       werft log result -d "build job" url "https://werft.gitpod-dev.com/job/${BUILD_ID}"
@@ -85,25 +147,40 @@ pod:
       echo "build success" | werft log slice "build test environment"
       werft log slice "build test environment" --done
 
+      werft log phase "kubectx" "kubectx"
+      mkdir -p /home/gitpod/.ssh
+      /workspace/dev/preview/util/download-and-merge-harvester-kubeconfig.sh | werft log slice "kubectx"
+      /workspace/dev/preview/install-k3s-kubeconfig.sh | werft log slice "kubectx"
+      werft log slice "kubectx" --done
+
       werft log phase "integration test" "integration test"
-      # we need get integration-test version like: jp-run-integration-test.61
+      args=()
+      args+=( "-kubeconfig=/home/gitpod/.kube/config" )
+      args+=( "-namespace=default" )
+      [[ "$USERNAME" != "" ]] && args+=( "-username=$USERNAME" )
 
-      oci-tool fetch file eu.gcr.io/gitpod-core-dev/build/versions:${BUILD_ID:13} versions.yaml
-      INTEGRATION_VERSION=$(cat versions.yaml | yq r - 'components.integrationTest.version')
+      IDE_TEST_LIST=(/workspace/test/tests/ide/vscode)
+      for TEST_PATH in "${IDE_TEST_LIST[@]}"
+      do
+          TEST_NAME=$(basename "${TEST_PATH}")
+          echo "running integration for ${TEST_NAME}" | werft log slice "test-${TEST_NAME}"
 
-      echo "using integration-test image: ${INTEGRATION_VERSION}" | werft log slice "test"
+          cd "${TEST_PATH}"
+          set +e
+          go test -v ./... "${args[@]}" 2>&1 | tee "${TEST_NAME}".log | werft log slice "test-${TEST_NAME}"
+          RC=${PIPESTATUS[0]}
+          set -e
 
-      NAMESPACE="$(preview-name-from-branch)"
-      TEST_BUILD_ID=$(werft run github -a version=${INTEGRATION_VERSION} -a namespace=staging-${NAMESPACE} --remote-job-path .werft/ide-run-integration-tests.yaml -a testPattern=vscode.test)
+          RUN_COUNT=$((RUN_COUNT+1))
+          if [ "${RC}" -ne "0" ]; then
+            FAILURE_COUNT=$((FAILURE_COUNT+1))
+            FAILURE_TESTS["${TEST_NAME}"]=$(grep "\-\-\- FAIL: " "${TEST_PATH}"/"${TEST_NAME}".log)
+            werft log slice "test-${TEST_NAME}" --fail "${RC}"
+          else
+            werft log slice "test-${TEST_NAME}" --done
+          fi
+      done
 
-      echo "running integration, job name: ${TEST_BUILD_ID}" | werft log slice "test"
-      werft log result -d "integration test job" url "https://werft.gitpod-dev.com/job/${TEST_BUILD_ID}"
-
-      if ! werft job logs ${TEST_BUILD_ID} | werft log slice "test";
-      then
-          echo "integration test failed" | werft log slice "test"
-          exit 1
-      fi
-      echo "integration test success" | werft log slice "test"
+      exit $FAILURE_COUNT
 plugins:
   cron: "0 3 * * *"
