precommit

diff --git a/components/BUILD.yaml b/components/BUILD.yaml
--- a/components/BUILD.yaml
+++ b/components/BUILD.yaml
@@ -196,6 +196,21 @@ scripts:
         popd > /dev/null
       done
 
+  - name: check-mocha-no-only
+    srcs:
+      - components/**/*
+    script: |
+      RED='\033[0;31m'
+
+      if [ "$(git diff --cached | grep "+" | grep ".only")" != "" ]; then
+        echo ""
+        echo "${RED}COMMIT FAILED:"
+        echo "${RED}Some spec files have .only. Please remove only and try committing again."
+        exit 1
+      else
+        exit 0
+      fi
+
   - name: unblock-user
     deps:
       - components/service-waiter:app
