modify Dockerfiles.

diff --git a/contrib/docker/gitpod-image/Dockerfile b/contrib/docker/gitpod-image/Dockerfile
--- a/contrib/docker/gitpod-image/Dockerfile
+++ b/contrib/docker/gitpod-image/Dockerfile
@@ -3,11 +3,29 @@
 
 FROM rancher/k3s:v1.21.2-k3s1
 
-ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-static /tini
-RUN chmod +x /tini
+# TODO: need to download https protocol
+ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-static-arm64 /tini-arm64
+RUN chmod +x /tini-arm64
+ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-static-amd64 /tini-amd64
+RUN chmod +x /tini-amd64
 
-ADD https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 /bin/yq
-RUN chmod +x /bin/yq
+ADD https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_arm64 /bin/yq-arm64
+RUN chmod +x /bin/yq-arm64
+ADD https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64 /bin/yq-amd64
+RUN chmod +x /bin/yq-amd64
+
+RUN arch="$(uname -m)"; \
+	case "$arch" in \
+		'x86_64') \
+			mv /tini-amd64 /tini \
+			mv /bin/yq-amd64 /bin/yq \
+			;; \
+		'aarch64') \
+			mv /tini-arm64 /tini \
+			mv /bin/yq-arm64 /bin/yq \
+			;; \
+		*) echo >&2 "error: unsupported architecture '$arch'"; exit 1 ;; \
+	esac;
 
 VOLUME /var/gitpod/docker
 VOLUME /var/gitpod/docker-registry
