[action] skip update image if it's failed to resolve (#19784)

diff --git a/.github/workflows/update-image-digest.yml b/.github/workflows/update-image-digest.yml
--- a/.github/workflows/update-image-digest.yml
+++ b/.github/workflows/update-image-digest.yml
@@ -50,10 +50,14 @@ jobs:
                     continue
                   fi
                   echo "Processing ${images2[i]} in file $file"
-                  updated_digest=$(crane digest "${images2[i]}")
-                  if [ "$updated_digest" != "${digests2[i]}" ] && [ -n "$updated_digest" ]; then
-                    echo "Digest ${digests2[i]} for image ${images2[i]} is different, new digest is $updated_digest, updating..."
-                    sed -i -e "s/${digests2[i]}/$updated_digest/g" "$file"
+                  updated_digest=$(crane digest "${images2[i]}" || true)
+                  if [ -n "$updated_digest" ]; then
+                      if [ "$updated_digest" != "${digests2[i]}" ]; then
+                          echo "Digest ${digests2[i]} for image ${images2[i]} is different, new digest is $updated_digest, updating..."
+                          sed -i -e "s/${digests2[i]}/$updated_digest/g" "$file"
+                      fi
+                  else
+                      echo "Failed to get digest for image ${images2[i]}, skipping..."
                   fi
                 done
             fi
